<!-- Generated by tools/program_slides.py; edit the data there, not here. -->

## {#s2-0 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-0">II семестър: от каталога към програмата на студента</div><div class="a-cap" data-id="cap-0">Каталогът предлага курсове; програмната схема казва колко и от какъв вид. Общо 30 кредита.</div><div class="shelf-h" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog" data-id="ADMB041" style="left:0px;top:226px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog" data-id="ADMB834" style="left:166px;top:226px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long" data-id="BAEB035" style="left:332px;top:226px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long" data-id="BUBB201" style="left:664px;top:226px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog" data-id="BUBB401" style="left:830px;top:226px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long" data-id="GENB015" style="left:1040px;top:226px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen" data-id="OOLE511" style="left:332px;top:414px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen" data-id="OOOK800" style="left:1040px;top:414px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen" data-id="OOOK064" style="left:332px;top:602px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="row-h" data-id="rowlabel" style="left:0px;top:756px;">Програма на студента · II семестър</div><div class="counter" data-id="counter" style="top:724px;">0 / 30 кр.</div></div>
```

::: {.notes}
[7:00] Пример: как един студент попълва II семестър. Каталогът предлага курсове; програмната схема казва колко и от какъв вид. Пет клика до пълния семестър.

Това е пример за един студент: изборът е индивидуален.
:::

## {#s2-1 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-0">II семестър: от каталога към програмата на студента</div><div class="a-cap" data-id="cap-1">1 · Курсове от програмата: 5 от предложените 6, общо 15 кредита.</div><div class="shelf-h" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog moving" data-id="ADMB041" style="left:0px;top:824px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog moving" data-id="ADMB834" style="left:166px;top:824px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long moving" data-id="BAEB035" style="left:332px;top:824px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong off" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long moving" data-id="BUBB201" style="left:498px;top:824px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog moving" data-id="BUBB401" style="left:664px;top:824px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long" data-id="GENB015" style="left:1040px;top:226px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen" data-id="OOLE511" style="left:332px;top:414px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen" data-id="OOOK800" style="left:1040px;top:414px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen" data-id="OOOK064" style="left:332px;top:602px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="badge" data-id="b-BAEB045" style="left:498px;top:350px;">не е избран · 5 от 6</div><div class="row-h" data-id="rowlabel" style="left:0px;top:756px;">Програма на студента · II семестър</div><div class="counter" data-id="counter" style="top:724px;">15 / 30 кр.</div></div>
```

::: {.notes}
Пет от шестте курса на програмата. Един остава: тук не е избран „Вземане на бизнес решения на базата на данни“.
:::

## {#s2-2 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-0">II семестър: от каталога към програмата на студента</div><div class="a-cap" data-id="cap-2">2 · Двусеместриалните курсове продължават от I семестър: GENB и български език.</div><div class="shelf-h" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog" data-id="ADMB041" style="left:0px;top:824px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog" data-id="ADMB834" style="left:166px;top:824px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long" data-id="BAEB035" style="left:332px;top:824px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong off" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long" data-id="BUBB201" style="left:498px;top:824px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog" data-id="BUBB401" style="left:664px;top:824px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long moving" data-id="GENB015" style="left:830px;top:824px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long off" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen" data-id="OOLE511" style="left:332px;top:414px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen moving" data-id="OOOK800" style="left:1328px;top:824px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong off" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen" data-id="OOOK064" style="left:332px;top:602px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="badge" data-id="b-BAEB045" style="left:498px;top:350px;">не е избран · 5 от 6</div><div class="badge cont" data-id="b-GENB015" style="left:830px;top:794px;">↻ от I семестър</div><div class="badge cont" data-id="b-OOOK800" style="left:1328px;top:794px;">↻ от I семестър</div><div class="row-h" data-id="rowlabel" style="left:0px;top:756px;">Програма на студента · II семестър</div><div class="counter" data-id="counter" style="top:724px;">21 / 30 кр.</div></div>
```

::: {.notes}
Двусеместриалните курсове продължават от I семестър: GENB и българският език, втората им половина (2/2).
:::

## {#s2-3 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-0">II семестър: от каталога към програмата на студента</div><div class="a-cap" data-id="cap-3">3 · Чужд език според нивото: 6 кредита.</div><div class="shelf-h" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog" data-id="ADMB041" style="left:0px;top:824px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog" data-id="ADMB834" style="left:166px;top:824px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long" data-id="BAEB035" style="left:332px;top:824px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong off" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long" data-id="BUBB201" style="left:498px;top:824px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog" data-id="BUBB401" style="left:664px;top:824px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long" data-id="GENB015" style="left:830px;top:824px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long off" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen off" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen moving" data-id="OOLE511" style="left:996px;top:824px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen off" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen" data-id="OOOK800" style="left:1328px;top:824px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong off" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen" data-id="OOOK064" style="left:332px;top:602px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="badge" data-id="b-BAEB045" style="left:498px;top:350px;">не е избран · 5 от 6</div><div class="badge cont" data-id="b-GENB015" style="left:830px;top:794px;">↻ от I семестър</div><div class="badge cont" data-id="b-OOOK800" style="left:1328px;top:794px;">↻ от I семестър</div><div class="row-h" data-id="rowlabel" style="left:0px;top:756px;">Програма на студента · II семестър</div><div class="counter" data-id="counter" style="top:724px;">27 / 30 кр.</div></div>
```

::: {.notes}
Чуждият език е според нивото: 6 кредита. Това е последният семестър с чужд език.
:::

## {#s2-4 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-0">II семестър: от каталога към програмата на студента</div><div class="a-cap" data-id="cap-4">4 · Един курс за знания, по правило от друга област: 3 кредита. Семестърът е пълен.</div><div class="shelf-h" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog" data-id="ADMB041" style="left:0px;top:824px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog" data-id="ADMB834" style="left:166px;top:824px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long" data-id="BAEB035" style="left:332px;top:824px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong off" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long" data-id="BUBB201" style="left:498px;top:824px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog" data-id="BUBB401" style="left:664px;top:824px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long" data-id="GENB015" style="left:830px;top:824px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long off" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen off" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen" data-id="OOLE511" style="left:996px;top:824px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen off" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen" data-id="OOOK800" style="left:1328px;top:824px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong off" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen off" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen off" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen moving" data-id="OOOK064" style="left:1494px;top:824px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen off" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen off" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen off" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long off" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long off" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="badge" data-id="b-BAEB045" style="left:498px;top:350px;">не е избран · 5 от 6</div><div class="badge cont" data-id="b-GENB015" style="left:830px;top:794px;">↻ от I семестър</div><div class="badge cont" data-id="b-OOOK800" style="left:1328px;top:794px;">↻ от I семестър</div><div class="row-h" data-id="rowlabel" style="left:0px;top:756px;">Програма на студента · II семестър</div><div class="counter full" data-id="counter" style="top:724px;">30 / 30 кр. ✓</div></div>
```

::: {.notes}
Един курс за знания, по правило от друга област. 30 от 30: семестърът е пълен.
:::

## {#s2-5 .anim-slide auto-animate=true}
```{=html}
<div class="anim"><div class="a-eyebrow" data-id="eyebrow">Пример · II семестър</div><div class="a-title" data-id="title-1">Схемата казва колко, каталогът казва кои</div><div class="a-cap" data-id="cap-5">Същият ред като II семестър в картата, но с курсовете на един студент.</div><div class="shelf-h gone" data-id="sh-prog" style="left:0px;top:192px;">Курсове от програмата · избират се 5 от 6</div><div class="shelf-h gone" data-id="sh-genb" style="left:1040px;top:192px;">GENB · продължава от I семестър</div><div class="shelf-h gone" data-id="sh-fl" style="left:0px;top:380px;">Чужд език · според нивото (6 езика, A1–C2)</div><div class="shelf-h gone" data-id="sh-bg" style="left:1040px;top:380px;">Български език · продължава</div><div class="shelf-h gone" data-id="sh-kn" style="left:0px;top:568px;">Курсове за знания · 1 по избор (77 в каталога)</div><div class="more gone" data-id="more" style="left:1344px;top:640px;">+ още 69</div><div class="slot k-prog gone" data-id="slot-0" style="left:0px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog gone" data-id="slot-1" style="left:166px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog gone" data-id="slot-2" style="left:332px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog gone" data-id="slot-3" style="left:498px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-prog gone" data-id="slot-4" style="left:664px;top:824px;width:158px;">курс от програмата<br><b>3 кр.</b></div><div class="slot k-genb gone" data-id="slot-5" style="left:830px;top:824px;width:158px;">GENB<br><b>2/2</b></div><div class="slot k-gen gone" data-id="slot-6" style="left:996px;top:824px;width:324px;">чужд език<br><b>6 кр.</b></div><div class="slot k-gen gone" data-id="slot-8" style="left:1328px;top:824px;width:158px;">български език<br><b>2/2</b></div><div class="slot k-gen gone" data-id="slot-9" style="left:1494px;top:824px;width:158px;">курс за знания<br><b>3 кр.</b></div><div class="c k-prog" data-id="ADMB041" style="left:0px;top:660px;width:158px;"><div class="code">ADMB041 · 3 кр.</div><div class="t">Управленска етика</div></div><div class="c k-prog" data-id="ADMB834" style="left:166px;top:660px;width:158px;"><div class="code">ADMB834 · 3 кр.</div><div class="t">Политики на ЕС</div></div><div class="c k-prog long" data-id="BAEB035" style="left:332px;top:660px;width:158px;"><div class="code">BAEB035 · 3 кр.</div><div class="t">Икономическа (бизнес) статистика</div></div><div class="c k-prog xlong off gone" data-id="BAEB045" style="left:498px;top:226px;width:158px;"><div class="code">BAEB045 · 3 кр.</div><div class="t">Вземане на бизнес решения на базата на данни</div></div><div class="c k-prog long" data-id="BUBB201" style="left:498px;top:660px;width:158px;"><div class="code">BUBB201 · 3 кр.</div><div class="t">Принципи на макро­икономиката</div></div><div class="c k-prog" data-id="BUBB401" style="left:664px;top:660px;width:158px;"><div class="code">BUBB401 · 3 кр.</div><div class="t">Правни анализи</div></div><div class="c k-genb long" data-id="GENB015" style="left:830px;top:660px;width:158px;"><div class="code">GENB015 · 2/2</div><div class="t">Държавно и публично управление</div></div><div class="c k-genb long off gone" data-id="GENB091" style="left:1206px;top:226px;width:158px;"><div class="code">GENB091 · 2/2</div><div class="t">Право, политика, цивилизация</div></div><div class="c k-gen off gone" data-id="OOLE312" style="left:0px;top:414px;width:324px;"><div class="code">OOLE312 · 6 кр.</div><div class="t">Английски език, B1</div></div><div class="c k-gen" data-id="OOLE511" style="left:996px;top:660px;width:324px;"><div class="code">OOLE511 · 6 кр.</div><div class="t">Английски език, B2</div></div><div class="c k-gen off gone" data-id="OOLE221" style="left:664px;top:414px;width:324px;"><div class="code">OOLE221 · 6 кр.</div><div class="t">Немски език, A2</div></div><div class="c k-gen" data-id="OOOK800" style="left:1328px;top:660px;width:158px;"><div class="code">OOOK800 · 2/2</div><div class="t">Български език</div></div><div class="c k-gen xlong off gone" data-id="OOOK805" style="left:1206px;top:414px;width:158px;"><div class="code">OOOK805 · 2/2</div><div class="t">Бълг. език – академично писане и говорене</div></div><div class="c k-gen off gone" data-id="OOOK051" style="left:0px;top:602px;width:158px;"><div class="code">OOOK051 · 3 кр.</div><div class="t">Старогръцка култура</div></div><div class="c k-gen off gone" data-id="OOOK109" style="left:166px;top:602px;width:158px;"><div class="code">OOOK109 · 3 кр.</div><div class="t">Що е фотография</div></div><div class="c k-gen" data-id="OOOK064" style="left:1494px;top:660px;width:158px;"><div class="code">OOOK064 · 3 кр.</div><div class="t">Астрономия и астрофизика</div></div><div class="c k-gen off gone" data-id="OOOK159" style="left:498px;top:602px;width:158px;"><div class="code">OOOK159 · 3 кр.</div><div class="t">Между­културна комуникация</div></div><div class="c k-gen off gone" data-id="OOOK233" style="left:664px;top:602px;width:158px;"><div class="code">OOOK233 · 3 кр.</div><div class="t">История на музиката</div></div><div class="c k-gen off gone" data-id="OOOK287" style="left:830px;top:602px;width:158px;"><div class="code">OOOK287 · 3 кр.</div><div class="t">Геология за всеки</div></div><div class="c k-gen long off gone" data-id="OOOK325" style="left:996px;top:602px;width:158px;"><div class="code">OOOK325 · 3 кр.</div><div class="t">Ораторско майсторство</div></div><div class="c k-gen long off gone" data-id="OOOK107" style="left:1162px;top:602px;width:158px;"><div class="code">OOOK107 · 3 кр.</div><div class="t">Съкровищата на България</div></div><div class="badge gone" data-id="b-BAEB045" style="left:498px;top:350px;">не е избран · 5 от 6</div><div class="badge cont" data-id="b-GENB015" style="left:830px;top:630px;">↻ от I семестър</div><div class="badge cont" data-id="b-OOOK800" style="left:1328px;top:630px;">↻ от I семестър</div><div class="row-h" data-id="rowlabel" style="left:0px;top:592px;">Програма на студента: кои курсове</div><div class="counter full" data-id="counter" style="top:560px;">30 / 30 кр. ✓</div><div class="row-h" data-id="schemalabel" style="left:0px;top:372px;">Програмна схема: колко и от какъв вид</div><div class="seg k-prog" data-id="seg-0" style="left:0px;top:408px;width:822px;"><b>Курсове от програмата</b><span>15 кр. · 5 от 6 курса</span></div><div class="seg k-genb" data-id="seg-1" style="left:830px;top:408px;width:158px;"><b>GENB</b><span>1 от 2</span></div><div class="seg k-gen" data-id="seg-2" style="left:996px;top:408px;width:324px;"><b>Чужд език</b><span>6 кр.</span></div><div class="seg k-gen" data-id="seg-3" style="left:1328px;top:408px;width:158px;"><b>Бълг. език</b><span>3 кр.</span></div><div class="seg k-gen" data-id="seg-4" style="left:1494px;top:408px;width:158px;"><b>Знания</b><span>3 кр.</span></div></div>
```

::: {.notes}
Схемата казва колко, каталогът казва кои. Горният ред е II семестър от картата на кредитите; долният е същият семестър с конкретните курсове на един студент.
:::

